### ISSUE TITLE
Brilliant Thank you

### ISSUE THREAD

**Issue by PythonLinks** [knolleary/twitter-to-mqtt#1]
I need this.  
I am surprised to see that 5 people used this in 2012, and no one since. 
I wonder what those forks changed. 

It would be great if it could publish different twitter feeds to diffrent topics. 

It would be great if it used the mqtt class example. 
https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_sub-class.py

It would be great if shutdown were a little more graceful. 

I wonder if the twitter api has changed since then?

Thanks for all fo the hard work.

**Comment by knolleary** [comment]
Thanks for the comments.

I haven't used this code in a number of years. The Twitter API has changed a lot since then and I doubt this will work anymore. I have no use for it, and am unlikely to spend any time updating it.

I hope it proves a useful reference point for someone who wants to do similar.
